# Generated by Django 5.1.7 on 2026-04-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
