# Generated by Django 6.0.6 on 2026-06-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_address_is_default_alter_address_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='delivery_city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='delivery_house',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='delivery_mobile',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='delivery_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='delivery_pincode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='delivery_state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='delivery_street',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
