# Generated by Django 6.0.6 on 2026-06-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_orderhistory_delivery_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='cancel_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Out of Stock', 'Out of Stock')], default='Pending', max_length=30),
        ),
    ]
